export interface TimeTableSlot{
      id?,
      year?,
      classCode?,
      className?,
      classNo?,
      subjectCode?,
      subjectName,
      lectureWeekType,
      Day,
      lectureNo,
      lectureHall?,
      lectureType?,
      createdAt?,
      updatedAt?,
}
